index:
    path: /
    controller: App\Controller\HomeController::indexAction

# LOGOWANIE

login:
    path:       /login
    controller: App\Controller\SecurityController::loginAction

register:
    path:       /register
    controller: App\Controller\SecurityController::registerAction

logout:
    path:       /logout

# POSIŁKI

mealType:
    path:       /meal/add-meal-type
    controller: App\Controller\MealController::addMealTypeAction